QT.tdesktopenvironment.VERSION = 1.0
QT.tdesktopenvironment.MAJOR_VERSION = 1
QT.tdesktopenvironment.MINOR_VERSION = 1
QT.tdesktopenvironment.name = tdesktopenvironment
QT.tdesktopenvironment.module = tdesktopenvironment
QT.tdesktopenvironment.depends = core dbus thelib
QT.tdesktopenvironment.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/libtdesktopenvironment/
QT.tdesktopenvironment.libs = $$QT_MODULE_LIB_BASE
QT_MODULES += tdesktopenvironment
