/****************************************
 *
 *   INSERT-PROJECT-NAME-HERE - INSERT-GENERIC-NAME-HERE
 *   Copyright (C) 2021 Victor Tran
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * *************************************/
#ifndef WAYLANDKEYBOARDTABLES_H
#define WAYLANDKEYBOARDTABLES_H

#include <QMultiMap>

#define NaN 0

namespace TWayland {
    const QMultiMap<Qt::Key, quint32> keymap = {
        {Qt::Key_Escape, 1},
        {Qt::Key_Tab, 15},
        {Qt::Key_Backspace, 14},
        {Qt::Key_Return, 28},
        {Qt::Key_Enter, 28},
        {Qt::Key_Enter, 96},
        {Qt::Key_Insert, 110},
        {Qt::Key_Delete, 111},
        {Qt::Key_Pause, 119},
        {Qt::Key_Print, 210},
        {Qt::Key_SysReq, 99},
        {Qt::Key_Clear, 355},
        {Qt::Key_Home, 102},
        {Qt::Key_End, 107},
        {Qt::Key_Left, 105},
        {Qt::Key_Up, 103},
        {Qt::Key_Right, 106},
        {Qt::Key_Down, 108},
        {Qt::Key_PageUp, 104},
        {Qt::Key_PageDown, 109},
        {Qt::Key_Shift, 42},
        {Qt::Key_Shift, 54},
        {Qt::Key_Control, 29},
        {Qt::Key_Control, 97},
        {Qt::Key_Meta, 125},
        {Qt::Key_Meta, 126},
        {Qt::Key_Alt, 56},
        {Qt::Key_Alt, 100},
        {Qt::Key_AltGr, 56},
        {Qt::Key_AltGr, 100},
        {Qt::Key_CapsLock, 58},
        {Qt::Key_NumLock, 69},
        {Qt::Key_ScrollLock, 70},
        {Qt::Key_F1, 59},
        {Qt::Key_F2, 60},
        {Qt::Key_F3, 61},
        {Qt::Key_F4, 62},
        {Qt::Key_F5, 63},
        {Qt::Key_F6, 64},
        {Qt::Key_F7, 65},
        {Qt::Key_F8, 66},
        {Qt::Key_F9, 67},
        {Qt::Key_F10, 68},
        {Qt::Key_F11, 87},
        {Qt::Key_F12, 88},
        {Qt::Key_F13, 183},
        {Qt::Key_F14, 184},
        {Qt::Key_F15, 185},
        {Qt::Key_F16, 186},
        {Qt::Key_F17, 187},
        {Qt::Key_F18, 188},
        {Qt::Key_F19, 189},
        {Qt::Key_F20, 190},
        {Qt::Key_F21, 191},
        {Qt::Key_F22, 192},
        {Qt::Key_F23, 193},
        {Qt::Key_F24, 194},
        {Qt::Key_Super_L, 125},
        {Qt::Key_Super_R, 126},
        {Qt::Key_Menu, 139},
        {Qt::Key_Help, 138},
        {Qt::Key_Space, 57},
        {Qt::Key_Dollar, 434},
        {Qt::Key_Apostrophe, 40},
        {Qt::Key_Comma, 51},
        {Qt::Key_Minus, 12},
        {Qt::Key_Slash, 53},
        {Qt::Key_0, 11},
        {Qt::Key_1, 2},
        {Qt::Key_2, 3},
        {Qt::Key_3, 4},
        {Qt::Key_4, 5},
        {Qt::Key_5, 6},
        {Qt::Key_6, 7},
        {Qt::Key_7, 8},
        {Qt::Key_8, 9},
        {Qt::Key_9, 10},
        {Qt::Key_Semicolon, 39},
        {Qt::Key_Equal, 13},
        {Qt::Key_Question, 214},
        {Qt::Key_A, 30},
        {Qt::Key_B, 48},
        {Qt::Key_C, 46},
        {Qt::Key_D, 32},
        {Qt::Key_E, 18},
        {Qt::Key_F, 33},
        {Qt::Key_G, 34},
        {Qt::Key_H, 35},
        {Qt::Key_I, 23},
        {Qt::Key_J, 36},
        {Qt::Key_K, 37},
        {Qt::Key_L, 38},
        {Qt::Key_M, 50},
        {Qt::Key_N, 49},
        {Qt::Key_O, 24},
        {Qt::Key_P, 25},
        {Qt::Key_Q, 16},
        {Qt::Key_R, 19},
        {Qt::Key_S, 31},
        {Qt::Key_T, 20},
        {Qt::Key_U, 22},
        {Qt::Key_V, 47},
        {Qt::Key_W, 17},
        {Qt::Key_X, 45},
        {Qt::Key_Y, 21},
        {Qt::Key_Z, 44},
        {Qt::Key_Backslash, 43},
        {Qt::Key_yen, 124},
        {Qt::Key_Muhenkan, 94},
        {Qt::Key_Henkan, 92},
        {Qt::Key_Hiragana, 91},
        {Qt::Key_Katakana, 90},
        {Qt::Key_Back, 158},
        {Qt::Key_Forward, 159},
        {Qt::Key_Stop, 128},
        {Qt::Key_Refresh, 173},
        {Qt::Key_VolumeDown, 114},
        {Qt::Key_VolumeUp, 115},
        {Qt::Key_BassBoost, 209},
        {Qt::Key_MediaPrevious, 165},
        {Qt::Key_MediaNext, 163},
        {Qt::Key_HomePage, 172},
        {Qt::Key_Favorites, 364},
        {Qt::Key_Search, 217},
        {Qt::Key_MonBrightnessUp, 225},
        {Qt::Key_MonBrightnessDown, 224},
        {Qt::Key_KeyboardLightOnOff, 228},
        {Qt::Key_KeyboardBrightnessUp, 229},
        {Qt::Key_KeyboardBrightnessDown, 230},
        {Qt::Key_WakeUp, 143},
        {Qt::Key_ScreenSaver, 581},
        {Qt::Key_WWW, 150},
        {Qt::Key_Memo, 396},
        {Qt::Key_Shop, 221},
        {Qt::Key_Finance, 219},
        {Qt::Key_CD, 383},
        {Qt::Key_Close, 206},
        {Qt::Key_Copy, 133},
        {Qt::Key_Cut, 137},
        {Qt::Key_Documents, 235},
        {Qt::Key_LogOff, 433},
        {Qt::Key_News, 427},
        {Qt::Key_Option, 357},
        {Qt::Key_Paste, 135},
        {Qt::Key_Phone, 169},
        {Qt::Key_Calendar, 397},
        {Qt::Key_Reply, 232},
        {Qt::Key_Save, 234},
        {Qt::Key_Send, 231},
        {Qt::Key_Video, 393},
        {Qt::Key_Xfer, 147},
        {Qt::Key_ZoomIn, 418},
        {Qt::Key_ZoomOut, 419},
        {Qt::Key_Messenger, 430},
        {Qt::Key_Battery, 236},
        {Qt::Key_Bluetooth, 237},
        {Qt::Key_WLAN, 238},
        {Qt::Key_UWB, 239},
        {Qt::Key_Subtitle, 370},
        {Qt::Key_Time, 359},
        {Qt::Key_Suspend, 205},
        {Qt::Key_MicMute, 248},
        {Qt::Key_Red, 398},
        {Qt::Key_Green, 399},
        {Qt::Key_Yellow, 400},
        {Qt::Key_Blue, 401},
        {Qt::Key_ChannelUp, 402},
        {Qt::Key_ChannelDown, 403},
        {Qt::Key_Info, 358},
        {Qt::Key_New, 181},
        {Qt::Key_Open, 134},
        {Qt::Key_Find, 136},
        {Qt::Key_Undo, 131},
        {Qt::Key_Redo, 182},
        {Qt::Key_unknown, 240},
        {Qt::Key_Camera, 212},
        {Qt::Key_Select, 353},
        {Qt::Key_Play, 207},
        {Qt::Key_Sleep, 142},
        {Qt::Key_Zoom, NaN},
        {Qt::Key_Exit, 174},
        {Qt::Key_Cancel, 223},
    };

    QList<quint32> toEvdevCodes(Qt::Key key);
    quint32 toEvdevMod(Qt::KeyboardModifiers mod);

    quint64 evdevDescriptor(quint32 mod, quint32 key);
    void breakoutEvdevDescriptor(quint64 descriptor, quint32* mod, quint32* key);
}

#undef NaN

#endif // WAYLANDKEYBOARDTABLES_H
